---
# tasks file for update-upgrade
- name: "Updating apt repo/cache"
  apt: 
   update_cache: yes 
   force_apt_get: yes
   cache_valid_time: 3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: 
   upgrade: "dist"
   force_apt_get: yes
   autoremove: true
   autoclean: true
  become: true
  become_method: sudo
  

