---
- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
  loop:
    - { repo: "https://github.com/Flangvik/SharpCollection", location: "/opt/SharpCollection" }
    - { repo: "https://github.com/danielmiessler/SecLists", location: "/opt/SecLists" }
  become: true
  become_method: sudo

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying python script to download github releases"
  copy:
    src: "files/githubdownload.py"
    dest: "{{ build_dir.path }}/githubdownload.py"
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: "Downloading github releases"
  shell: "{{ build_dir.path }}/githubdownload.py {{ item.repo }} {{ item.regex }} {{ item.location }} {% if item.filename is defined %}{{ item.filename }}{% endif %}"
  loop:
    - { repo: "obsidianmd/obsidian-releases",  regex: ".deb", location: "/tmp/obsidian" }
    - { repo: "jpillora/chisel",  regex: "_linux_amd64.gz", location: "/opt/chisel" }
    - { repo: "jpillora/chisel",  regex: "_windows_amd64.gz", location: "/opt/chisel" }
    #- { repo: "jpillora/chisel",  regex: "_darwin_amd64", location: "/opt/chisel", filename: "chisel_osx" }
    - { repo: "carlospolop/PEASS-ng",  regex: "linpeas.sh", location: "/opt/peas" }
    - { repo: "carlospolop/PEASS-ng",  regex: "winPEASx64.exe", location: "/opt/peas" }
    - { repo: "WithSecureLabs/chainsaw",  regex: "chainsaw_all_", location: "/opt/" }
    - { repo: "BloodHoundAD/BloodHound", regex: "BloodHound-linux-x64.zip", location: "/opt/" }
  async: 45
  poll: 0
  become: true
  become_method: sudo

- name: "Check DEB file of Obsidian"
  find:
    paths: "/tmp/obsidian"
    file_type: file
  register: found_files
# - name:
#   debug:
#     msg: "{{found_files.files}}"

- name: "Display found files"
  apt:
    deb: "{{ item.path }}"
    state: present
  when: "'deb' in item.path"
  loop: "{{ found_files.files }}"
  become: True
  become_method: sudo 

- name: Remove Obsidian Binary directory
  ansible.builtin.file:
    path: "/tmp/obsidian"
    state: absent
  when: "'deb' in item.path"
  loop: "{{ found_files.files }}"
  become: True
  become_method: sudo 

- name: Remove temporary build directory
  ansible.builtin.file:
    path: "{{ build_dir.path }}"
    state: absent
  when: build_dir.path is defined
  