" Enable syntax highlighting
syntax on

" Set tab width to 4 spaces
set tabstop=4
set shiftwidth=4
set expandtab

" enable file type 
filetype on

" Show line numbers
set number

" Enable mouse support
set mouse=a

" enable file list 
set list
