export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/icyb3r/.local/bin/:/home/icyb3r/.local/bin/personal"
export ZDOTDIR="/home/icyb3r/.config/zsh"
